title: Jonne Kats
description: "Blogging about Software development, .NET, Architecture, etc." 
meta_description: "Jonne Kats's technical blog about .NET, Architecture, Design and Sitecore"

aboutPage: false

markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"

paginate: 9
baseurl: /
domain_name: 'http://jonnekats.nl'
google_analytics: 'UA-77467893-1'
disqus: true
disqus_shortname: 'jonnekats'

# Details for the RSS feed generator
url:            'http://jonnekats.nl'
author:         'Jonne Kats'
authorTwitter:  'jonnekats'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

plugins: ["jekyll-paginate"]